version: '3.8'

services:
  postgreswriter:
    image: postgreswriter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - KAFKA_BROKER_GROUP_ID=${KAFKA_BROKER_GROUP_ID}
      - KAFKA_BROKER_SERVER_URL=${KAFKA_BROKER_SERVER_URL}
      - KAFKA_BROKER_PORT=${KAFKA_BROKER_PORT}
      - SAINT_CREATION_KAFKA_TOPIC=${SAINT_CREATION_KAFKA_TOPIC}
      - SAINT_UPDATE_KAFKA_TOPIC=${SAINT_UPDATE_KAFKA_TOPIC}
      - SAINT_DELETION_KAFKA_TOPIC=${SAINT_DELETION_KAFKA_TOPIC}
      - SAINT_LAKE_DB_CONNECTION_STRING=${SAINT_LAKE_DB_CONNECTION_STRING}
      - SAINT_LAKE_DB_USER=${SAINT_LAKE_DB_USER}
      - SAINT_LAKE_DB_PASSWORD=${SAINT_LAKE_DB_PASSWORD}
      - SAINT_LAKE_DB_TABLE_NAME=${SAINT_LAKE_DB_TABLE_NAME}
    ports:
      - 3069:80
    platform: linux/amd64
    restart: always

networks:
  default:
    name: local-network