version: '3.8'

services:
  saint-loader:
    image: saint-loader
    container_name: saint-loader
    hostname: saint-loader
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - KAFKA_BROKER_SERVER_URL=${KAFKA_BROKER_SERVER_URL}
      - KAFKA_BROKER_PORT=${KAFKA_BROKER_PORT}
      - KAFKA_BROKER_GROUP_ID=${KAFKA_BROKER_GROUP_ID}
      - SAINT_CREATION_KAFKA_TOPIC=${SAINT_CREATION_KAFKA_TOPIC}
      - SAINT_UPDATE_KAFKA_TOPIC=${SAINT_UPDATE_KAFKA_TOPIC}
      - SAINT_DELETION_KAFKA_TOPIC=${SAINT_DELETION_KAFKA_TOPIC}
      - SAINT_ANALYTICS_DB_HOST=${SAINT_ANALYTICS_DB_HOST}
      - SAINT_ANALYTICS_DB_PORT=${SAINT_ANALYTICS_DB_PORT}
      - SAINT_ANALYTICS_DB_DATABASE=${SAINT_ANALYTICS_DB_DATABASE}
      - SAINT_ANALYTICS_DB_USER=${SAINT_ANALYTICS_DB_USER}
      - SAINT_ANALYTICS_DB_PASSWORD=${SAINT_ANALYTICS_DB_PASSWORD}
      - SAINT_ANALYTICS_DB_TABLE_NAME=${SAINT_ANALYTICS_DB_TABLE_NAME}
    ports:
      - 3069:80
    platform: linux/amd64
    restart: always

networks:
  default:
    name: local-network
